services:

  httpd:
    image: docker.io/alvistack/httpd-2.4:latest
    env_file:
      - ./.env
    volumes:
      - ./.root/etc/apache2/sites-enabled/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./:/var/www/html
      - /tmp:/tmp
    ports:
      - 80

  php:
    image: docker.io/alvistack/php-8.3-fpm:latest
    env_file:
      - ./.env
    volumes:
      - ./.root/etc/php/fpm/pool.d/www.conf:/etc/php/fpm/pool.d/www.conf
      - ./:/var/www/html
      - /tmp:/tmp
    ports:
      - 9000

  mariadb:
    image: docker.io/alvistack/mariadb-11.8:latest
    env_file:
      - ./.env
    volumes:
      - ./.root/var/lib/mysql:/var/lib/mysql
      - /tmp:/tmp
    ports:
      - 3306

  memcached:
    image: docker.io/memcached:1.6
    env_file:
      - ./.env
    command:
      - /bin/bash
      - -c
      - memcached -m 64
    volumes:
      - /tmp:/tmp
    ports:
      - 11211

  postgres:
    image: docker.io/alvistack/postgres-18:latest
    env_file:
      - ./.env
    volumes:
      - ./.root/var/lib/postgresql/data:/var/lib/postgresql/data
      - /tmp:/tmp
    ports:
      - 5432

  redis:
    image: docker.io/redis:8.6
    env_file:
      - ./.env
    command:
      - /bin/bash
      - -c
      - redis-server --appendonly no --maxmemory 64mb --maxmemory-policy volatile-lru
    volumes:
      - /tmp:/tmp
    ports:
      - 6379

  solr:
    image: docker.io/solr:9.10
    env_file:
      - ./.env
    command:
      - /bin/bash
      - -c
      - solr-precreate default
    volumes:
      - ./modules/contrib/search_api_solr/jump-start/solr9/config-set:/opt/solr/server/solr/configsets/_default/conf
      - ./.root/var/solr:/var/solr
      - /tmp:/tmp
    ports:
      - 8983

  devel:
    image: docker.io/alvistack/devel-24.04:latest
    env_file:
      - ./.env
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - /tmp:/tmp
    ports:
      - 22
