---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: var-www-html
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  hostPath:
    path: "/vagrant"
