---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opt-solr-server-solr-configsets-default-conf
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
